version: "3"

services:
  development-server:
    environment:
      - PORT=${PORT:-7860}
      - HMR_PORT=${HMR_PORT:-7861}
    ports:
      - "${PORT:-7860}:7860"
      - "${HMR_PORT:-7861}:7861"
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/home/user/app/
    command:
      [
        "/usr/local/searxng/dockerfiles/docker-entrypoint.sh -f & npm install && npm run dev -- --host",
      ]
