name: Sync to Hugging Face Spaces
on:
  push:
    branches:
      - main
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Sync to Hugging Face Spaces
        uses: JacobLinCool/huggingface-sync@v1
        with:
          github: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ vars.HF_SPACE_OWNER }}
          space: ${{ vars.HF_SPACE_NAME }}
          token: ${{ secrets.HF_TOKEN }}
          title: MiniSearch
          emoji: 👌🔍
          short_description: Minimalist web-searching app with browser-based AI assistant
          colorFrom: yellow
          colorTo: yellow
          sdk: docker
          pinned: true
          header: mini
